### ISSUE TITLE
Image Transforms?

### ISSUE THREAD

**Issue by noahyamen** [radarseven/Craft-Twig-ImageBase64#2]
Is there a way to apply the image transforms to your base64 conversion?

**Comment by radarseven** [comment]
Hi @noahyamen, 

In theory, I should be able to add support for image transforms fairly easily. I haven't looked at this in a while, but I'll take a look at supporting this.

A question for you about how you're using image transforms. Do you typically define your image transforms in your Twig templates or with in the Craft control panel?

Thanks,
Michael

**Comment by noahyamen** [comment]
Defining the image transforms happens in the Craft CMS control panel. So for example, if you define a transform named "Thumbs" in the control panel settings, this would output it in your template: {{ asset.getUrl('thumbs') }}

**Comment by radarseven** [comment]
@noahyamen, image transforms can also be defined and applied directly in the Twig template as well. See [here](https://craftcms.com/docs/image-transforms#defining-transforms-in-your-templates).

In thinking about this more, I think it makes more sense to first perform the transform in the Twig template, then pass the transformed asset to the plugin. This will be the most flexible way to handle this, as a lot of developers are using the [Imager](https://github.com/aelvan/Imager-Craft) plugin.

-----

So, as in your example, you would do something like the following in your Twig template:

```
{# First, do the transform. In this case, apply the 'thumbs' transform from the CP. #}
{% do asset.setTransform('thumbs') %}

{# Pass the transformed asset to the plugin. #}
{{ image64(asset) }}
```

See [here](https://craftcms.com/docs/templating/assetfilemodel#setTransform) for reference on this approach.

-----

Give this a try and let me know how it works out for you.

**Comment by noahyamen** [comment]
That works! Great, thank you!
